### ISSUE TITLE
Use auto deploy to pypi

### ISSUE THREAD

**Issue by pomponchik** [petamas/oslex#9]
Hello!

I suspect that the reason for the [problems](https://github.com/petamas/oslex/issues/8) with uploading new versions of your library may be the fact that you do not use the workflow for auto-deploy.

I have an [example](https://github.com/pomponchik/cantok/blob/main/.github/workflows/release.yml) of it. You need create a file `.github/workflows/release.yml` with content like this:

```yaml
name: Release

on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
            python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash
        run: pip install -r requirements_dev.txt

      - name: Build the project
        shell: bash
        run: python -m build .

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
```

Also you need register a trusted publisher on pypi.
